export const DI_TOKENS = {
  WEATHER_API_CLIENT: Symbol('WEATHER_API_CLIENT'),
  SUBSCRIPTION_REPOSITORY: Symbol('SUBSCRIPTION_REPOSITORY'),
  EMAIL_SERVICE: Symbol('EMAIL_SERVICE'),
  WEATHER_SERVICE: Symbol('WEATHER_SERVICE'),
  SUBSCRIPTION_SERVICE: Symbol('SUBSCRIPTION_SERVICE'),
  LOGGER_SERVICE: Symbol('LOGGER_SERVICE'),
};